// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0hZiMhiVo2bY-gFUqWpJxlkP78EcxweI',
    appId: '1:41167658690:web:2834e0001cb2145d94a55b',
    messagingSenderId: '41167658690',
    projectId: 'gps-attendance-system-c73b3',
    authDomain: 'gps-attendance-system-c73b3.firebaseapp.com',
    storageBucket: 'gps-attendance-system-c73b3.firebasestorage.app',
    measurementId: 'G-2CCNZX2YT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB913iaxuPHbZ6j_ubPIDN8tKzvrXDE-wI',
    appId: '1:41167658690:android:21da03d77a23d4dc94a55b',
    messagingSenderId: '41167658690',
    projectId: 'gps-attendance-system-c73b3',
    storageBucket: 'gps-attendance-system-c73b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU8-kQTJzCuwp7bYZP-fCrjxFs7YFbtIo',
    appId: '1:41167658690:ios:b9edf2ab5f15647b94a55b',
    messagingSenderId: '41167658690',
    projectId: 'gps-attendance-system-c73b3',
    storageBucket: 'gps-attendance-system-c73b3.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.gps-attendance-system',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU8-kQTJzCuwp7bYZP-fCrjxFs7YFbtIo',
    appId: '1:41167658690:ios:25546557508d27fd94a55b',
    messagingSenderId: '41167658690',
    projectId: 'gps-attendance-system-c73b3',
    storageBucket: 'gps-attendance-system-c73b3.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0hZiMhiVo2bY-gFUqWpJxlkP78EcxweI',
    appId: '1:41167658690:web:34128e286f33a70c94a55b',
    messagingSenderId: '41167658690',
    projectId: 'gps-attendance-system-c73b3',
    authDomain: 'gps-attendance-system-c73b3.firebaseapp.com',
    storageBucket: 'gps-attendance-system-c73b3.firebasestorage.app',
    measurementId: 'G-LT69SBVH2H',
  );
}
